#!/usr/bin/env bash

temp="`mktemp -d`"
config="/home/$USER/.config/AIGoR"
mkdir -p "$config"
title=`cat "$config"/title`
width=`cat "$config"/width`
height=`cat "$config"/height`

 while :
	do
data=$(yad --width=600 --button=Ok:0 --button=Exit:1 --center --form \
            --title="AIGoR https://pollinations.ai/" \
            --text="Enter the following information to generate an image" \
            --center \
            --field="Prompt":TXT \
	     --field="Suggest Prompt":CB\
            --field="Width":NUM \
            --field="Height":NUM\
            --field="Seed (0 = Random)":NUM \
            --field="Engine":CB\
	    --field="Nologo":CHK \
	    --field="Enhance":CHK \
	    "$title" "None!Yes" "$width" "$height" "0" "flux!turbo" "true" "false") butt=$?
	 
echo $butt	 
if [ "$butt" = 1 ]; then	
	rm -rf "$temp" && exit 0
fi
	    
ans=$?
if [ $ans -eq 0 ]
then
    IFS="|" read -r -a array <<< "$data"
    
    if [ "${array[0]}" == "" ]
    then
    void=$(yad --width=300 --center --text "Prompt is void Retry or Exit?" \
--button=Retry:0 --button=Exit:1) ftest=$?
if [ "$ftest" = 1 ]; then	
	rm -rf "$temp" && exit 0
fi
if [ "$ftest" = 0 ]; then	
	 continue
fi
    fi
    echo "You have entered the following information:"
    echo Prompt: "${array[0]}"
    echo Suggest: "${array[1]}"
    echo Width: "${array[2]}"
    echo Height: "${array[3]}"
    echo Seed: "${array[4]}"
    echo Engine: "${array[5]}"
    echo Nologo: "${array[6]}"
    echo Enhance: "${array[7]}"
else
    echo "You deleted"
fi
title="${array[0]}"
width="${array[2]}"
height="${array[3]}"
echo "$title"> $config/title
echo "$width"> $config/width
echo "$height"> $config/height
enhance="${array[1]}"
seed="${array[4]}"
short="${title:0:200}"
short="${short//,}"
short="${short//:}"
#touch "$temp"/"$short"."$seed".jpg

if [ "$seed" = 0 ]; then	
	seed=$RANDOM
fi
echo Seed $seed

if [ "$enhance" = "Yes" ]; then	
	#echo "$enhance"
	wget --connect-timeout=20 --no-http-keep-alive -U "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)" --output-document="$temp"/"$short".txt https://text.pollinations.ai/prompt/"ten examples of enhance prompt for image generation in English ""$title" |  yad --progress --auto-close --center  --width=300 --title="Wait please..."
entext=$(yad  --title="Please remove the superfluous text." --center --width=800 --height=600 --editable --text-info --in-place --wrap --file-op < "$temp"/"$short".txt
)
#echo "$entext"
#cat vecchio\ scarpone.txt | grep '1\.' | sed  's/1.//'

wget --connect-timeout=20 --no-http-keep-alive -U "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)" --output-document="$temp"/"$short"."$seed".jpg https://image.pollinations.ai/prompt/"$entext"?width="${array[2]}"\&height="${array[3]}"\&model="${array[5]}"\&nologo="${array[6]}"\&seed="$seed"\&enhance="${array[7]}" |  yad --progress --auto-close --center  --width=300 --title="Wait please..."
fi

if [ "$enhance" = "None" ]; then
wget --connect-timeout=20 --no-http-keep-alive -U "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)" --output-document="$temp"/"$short"."$seed".jpg https://image.pollinations.ai/prompt/"$title"?width="${array[2]}"\&height="${array[3]}"\&model="${array[5]}"\&nologo="${array[6]}"\&seed="$seed"\&enhance="${array[7]}" |  yad --progress --auto-close --center  --width=300 --title="Wait please..."
fi
#sleep 15
viewpic=$(yad --center --picture --file-op \
  --title="Picture viewer" \
  --width=800 --height=600 \
 --button="Retry":4 --button="Open in Gimp":5  --button="Save and Retry":3 --button="Save and Exit":0 --button=Exit:1 \
  --filename="$temp"/"$short"."$seed".jpg) options=$?

echo $options

if [ "$options" = 0 ]; then	
	savepic=$(yad --file --save --filename="$temp"/"$short"."$seed".jpg) save=$?
	#echo  save "$save"
	echo pic "$savepic"
	mv "$temp"/"$short"."$seed".jpg "$savepic" && exit 0
fi

if [ "$options" = 3 ]; then	
	savepic=$(yad --file --save --filename="$temp"/"$short"."$seed".jpg) save=$?
	#echo  save "$save"
	echo pic "$savepic"
	mv "$temp"/"$short"."$seed".jpg "$savepic"
fi

if [ "$options" = 1 ]; then	
	rm -rf "$temp" && exit 0
fi

if [ "$options" = 5 ]; then	
	gimp "$temp"/"$short"."$seed".jpg
fi
if [ "$options" = 4 ]; then	
	echo "retry"
fi
done
rm -rf "$temp"
exit 0
